# Generated by Django 3.0.4 on 2020-03-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='x_c',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='y_c',
            field=models.IntegerField(default=0),
        ),
    ]
